In [7]:
t = ((1.0, 1.0), (0.3, 0.4), (1.0, 1.5), (3.0, 0.2), (3.5, -0.8), (4.5, -0.6), (3.5, -0.5))
l1 = [t[5], t[4], t[6], t[3]]
l2 = [t[0], t[1], t[2]]
xs1, ys1, xs2, ys2 = 0, 0, 0, 0
for i in l1:
    xs1 += i[0]
    ys1 += i[1]
xa1 = xs1 / len(l1)
ya1 = ys1 / len(l1)
for i in l2:
    xs2 += i[0]
    ys2 += i[1]
xa2 = xs2 / len(l2)
ya2 = ys2 / len(l2)
print((xa1, ya1), (xa2, ya2))

(3.625, -0.425) (0.7666666666666666, 0.9666666666666667)


In [8]:
c1 = (xa1, ya1)
c2 = (xa2, ya2)
for p in t:
    print("c1:", ((p[0]-c1[0])*(p[0]-c1[0])+(p[1]-c1[1])*(p[1]-c1[1])), "c2:", ((p[0]-c2[0])*(p[0]-c2[0])+(p[1]-c2[1])*(p[1]-c2[1])))

c1: 8.92125 c2: 0.05555555555555558
c1: 11.73625 c2: 0.5388888888888888
c1: 10.596250000000001 c2: 0.3388888888888889
c1: 0.78125 c2: 5.575555555555555
c1: 0.15625000000000006 c2: 10.592222222222222
c1: 0.79625 c2: 16.392222222222223
c1: 0.02125 c2: 9.622222222222224


In [10]:
75*12/25 -75*1/5 -75*4/15

1.0

In [17]:
import numpy as np
s = ((2.5, 3.0, 1), (3.0, 2.0, 1), (3.5, 3.0, 1), (5.0, 3.5, 0), (4.0, 4.5, 0), (4.0, 4.0, 0))
w = (15.2, -2.7, -2.2)
netinput = []
for i in s:
    netinput.append(round(1*w[0]+i[0]*w[1]+i[1]*w[2], 4))
for n in netinput:
    print(round(1 - np.exp(n)/(1+np.exp(n)), 6))

0.135873
0.062973
0.700567
0.997527
0.99593
0.987872


In [18]:
errors = (0.135873, 0.062973, 0.7006, -0.0025, -0.0041, -0.0121)
sa, sb = 0, 0
for i in range(6):
    sa += t[i][0] * errors[i]
    sb += t[i][1] * errors[i]
sa, sb

(0.7790649000000001, 1.2220022)

In [21]:
cost = 0
cost -= np.log(0.8445)
cost -= np.log(0.9278)
cost -= np.log(0.2617)
cost -= np.log(1-0.0019)
cost -= np.log(1-0.0032)
cost -= np.log(1-0.0097)
cost

1.5993603885382377

In [10]:
# Q4(1)GD
import numpy as np
err = np.array([[0.1040, 0.0482, 0.6203, -0.0039, -0.0064, -0.0186]])
x = np.array([[1, 2.5, 3.0], [1, 3.0, 2.0], [1, 3.5, 3.0], [1, 5.0, 3.5], [1, 4.0, 4.5], [1, 4.0, 4.0]])
np.dot(err, x)

array([[0.7436 , 2.45615, 2.15245]])

In [12]:
w0 = [15.2169, -2.6443, -2.1509]
g0 = [0.7436 , 2.4562, 2.1525]
round(w0[0]+g0[0]*0.01, 4), round(w0[1]+g0[1]*0.01, 4), round(w0[2]+g0[2]*0.01, 4)

(15.2243, -2.6197, -2.1294)

In [32]:
# w = np.array([[15.2, -2.7, -2.2]])
# w = np.array([[15.2088, -2.671, -2.1744]])
w = np.array([[15.2169, -2.6443, -2.1509]])
np.dot(w, x.T)

array([[-5.971619 ,  2.7171645]])

In [7]:
netinput = [ 2.1535,  2.9822 , -0.4909, -5.5328, -5.0394, -3.9639]
output=[]
for n in netinput:
    output.append(round(np.exp(n)/(1+np.exp(n)), 4))
output

[0.896, 0.9518, 0.3797, 0.0039, 0.0064, 0.0186]

In [8]:
errors = []
y = [1, 1, 1, 0, 0, 0]
for i in range(6):
    errors.append(round(y[i]-output[i], 4))
errors

[0.104, 0.0482, 0.6203, -0.0039, -0.0064, -0.0186]

In [9]:
cost = 0
for i in range(6):
    if y[i] == 1:
        cost -= np.log(output[i])
    else:
        cost -= np.log(1-output[i])
cost 

1.1566923760069878

In [95]:
# Q4(1) MGD
import numpy as np
idx = [4, 2]
xx = [[1, 2.5, 3.0], [1, 3.0, 2.0], [1, 3.5, 3.0], [1, 5.0, 3.5], [1, 4.0, 4.5], [1, 4.0, 4.0]]
x = np.array([xx[idx[0]], xx[idx[1]]])
# w = np.array([[15.2, -2.7, -2.2]])
print(w)
netinput = np.dot(w, x.T)
netinput = np.round(netinput, 6)
netinput

[[15.21805431 -2.64163953 -2.14812778]]


array([[-5.015079, -0.472067]])

In [96]:
print(netinput)
output=[]
for n in netinput[0]:
    output.append(round(np.exp(n)/(1+np.exp(n)), 6))
output = np.round(output, 6)
output

[[-5.015079 -0.472067]]


array([0.006593, 0.384127])

In [97]:
errors = []
y = [1, 1, 1, 0, 0, 0]
for i in range(2):
    errors.append(round(y[idx[i]]-output[i], 6))
errors

[-0.006593, 0.615873]

In [98]:
cost = 0
for i in range(2):
    if y[idx[i]] == 1:
        print(output[i])
        cost -= np.log(output[i])
    else:
        print(1-output[i])
        cost -= np.log(1-output[i])
round(cost, 6)

0.993407
0.384127


0.963397

In [99]:
err = np.array([errors])
x = np.array([xx[idx[0]], xx[idx[1]]])
gr = np.dot(err, x)
gr = np.round(gr, 6)
gr

array([[0.60928 , 2.129184, 1.81795 ]])

In [100]:
print(gr)
w = w+gr*0.01
np.round(w, 6)

[[0.60928  2.129184 1.81795 ]]


array([[15.224147, -2.620348, -2.129948]])

In [102]:
x = np.array([[1, 3.5, 4.0], [1, 6.0, 1.5], [1, 4.5, 3.3], [1, 4.0, 4.5]])
w = np.array([[21.7, -2.4, -3.8]])
print(w)
netinput = np.dot(w, x.T)
netinput = np.round(netinput, 6)
netinput

[[21.7 -2.4 -3.8]]


array([[-1.9 ,  1.6 , -1.64, -5.  ]])

In [103]:
print(netinput)
output=[]
for n in netinput[0]:
    output.append(round(np.exp(n)/(1+np.exp(n)), 6))
output = np.round(output, 6)
output

[[-1.9   1.6  -1.64 -5.  ]]


array([0.130108, 0.832018, 0.162465, 0.006693])

In [16]:
# Q4(2)
idx = [0, 1, 2]
xx = [[1, 3.5, 4.0], [1, 6.0, 1.5], [1, 4.5, 3.3]]
x = np.array([xx[0], xx[1], xx[2]])
w = np.array([[21.7, -2.4, -3.8]])
netinput = np.dot(w, x.T)
netinput

array([[-1.9 ,  1.6 , -1.64]])

In [47]:
output=[]
for n in netinput[0]:
    output.append(round(np.exp(n)/(1+np.exp(n)), 4))
output

[0.1301, 0.832, 0.1625]

In [48]:
errors = []
y = [1, 0, 1]
for i in range(3):
    errors.append(round(y[idx[i]]-output[i], 4))
errors

[0.8699, -0.832, 0.8375]

In [5]:
# Q1(1)
x = [[0, 0, 0, 0, 0, 0], [0, 0, 1, 2, 3, 0], [0, 4, 5, 6, 7, 0], [0, 8, 9, 10, 11, 0], [0, 12, 13, 14, 15, 0], [0, 0, 0, 0, 0, 0]]
w = [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]]
for i in range(4):
    for j in range(4):
        s = 0
        for p in range(3):
            for q in range(3):
                s += x[i+p][j+q]*w[p][q]
        print(i+1, j+1, round(s, 4))

1 1 8.3
1 2 13.9
1 3 17.8
1 4 12.1
2 1 19.8
2 2 30.3
2 3 34.8
2 4 22.5
3 1 33.0
3 2 48.3
3 3 52.8
3 4 33.3
4 1 18.1
4 2 25.3
4 3 27.4
4 4 16.3
